### ISSUE TITLE
h3 py crashing on apple silocon

### ISSUE THREAD

**Issue by geoHeil** [conda-forge/h3-py-feedstock#38]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from h3 import h3
[1]    19001 segmentation fault  python

### Installed packages

```shell
h3=3.7.4
```

### Environment info

```shell
apple silicon m2
```

**Comment by isuruf** [comment]
Looks like https://github.com/scikit-build/scikit-build/issues/589 was not fixed properly.

**Comment by Tobias-Fischer** [comment]
This has been fixed with #39 - it works nicely now on my M1.

@conda-forge/h3-py could you please close here?
