### ISSUE TITLE
Update Feedstock for 4.1.1 Release

### ISSUE THREAD

**Issue by bjlittle** [conda-forge/h3-py-feedstock#44]
@mxr-conda @bubblyorca @geoHeil

Are there plans to update the feedstock to support the recent [4.1.1](https://github.com/uber/h3-py/releases/tag/v4.1.1) release ?

As this is a major release the `conda-forge` and PyPI ecosystems are now not aligned which means that dependent projects require to hard pin on 3.7.7 before migrating to accommodate the breaking changes in the API.

Many thanks!

🙏

**Comment by geoHeil** [comment]
I do not have time now to fix it but @bjlittle if you can make the PR https://github.com/conda-forge/h3-py-feedstock/pull/43 here go green I guess we are fine with moving forward and supporting 4.1

**Comment by geoHeil** [comment]
Reason: see https://github.com/conda-forge/h3-py-feedstock/pull/43#issuecomment-2419855640 if you can help contribute a fix - it is probably not too hard the CI should be green again soon

**Comment by bjlittle** [comment]
@geoHeil Thanks 👍 

I might have some capacity to look into this and see if I can unpick the issue, particularly if it's just a missing dependency

**Comment by geoHeil** [comment]
merged your PR - thanks @bjlittle for your support
