### ISSUE TITLE
Broken Package

### ISSUE THREAD

**Issue by benhuff** [conda-forge/h3-py-feedstock#6]
Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because:

The noarch version of this package fails to find the dynamic libraries correctly. I was not aware of this until I attempted to install and use the package.

The other builds are causing issues because they are building and testing correctly on Azure (finding the dynamic libraries) but they are not recognizing the run dependencies when using ``conda install h3-py``.

from a fresh Python 3.7 conda environment:
```
(testing) % conda install h3-py
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/user/opt/anaconda3/envs/testing

  added / updated specs:
    - h3-py


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    h3-py-3.4.3                |             py_0          15 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          15 KB

The following NEW packages will be INSTALLED:

  h3-py              conda-forge/noarch::h3-py-3.4.3-py_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
h3-py-3.4.3          | 15 KB     | ####################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(testing) % conda list
# packages in environment at /Users/user/opt/anaconda3/envs/testing:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
h3-py                     3.4.3                      py_0    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
```
Conda install defaults to the noarch version and also does not install the run dependency ``h3``.

Similarly, running ``conda install https://anaconda.org/conda-forge/h3-py/3.4.3/download/osx-64/h3-py-3.4.3-py38_2.tar.bz2`` also does not install the run dependency ``h3``.

Any advice is appreciated, I have not built python bindings for a C package before. When I build and install this recipe locally (osx), it all works as expected: h3 and h3-py are installed and running the test ``python -c "from h3 import h3"`` is successful. 

It is important to me that the python bindings use the ``h3`` package from conda forge rather than building with the ``install.sh`` found in https://github.com/uber/h3-py/blob/master/.install.sh.

**Comment by geoHeil** [comment]
Do you know to reactivate the `https://github.com/conda-forge/staged-recipes/blob/master/.circleci/run_docker_build.sh` it seems that this is only available prior to this package becoming a regular feedstock. This might make debugging the issue easier and faster.

I tried to make our meta.yml look more like any other which looks fine and took inspiration from geopandas. You can find a pull request at https://github.com/conda-forge/h3-py-feedstock/pull/7

Potentially this helps.

**Comment by ocefpaf** [comment]
@benhuff do you mean to move all packages or just the noarch version? If the latter please check https://anaconda.org/conda-forge/h3-py/files and let me know if that is OK.

**Comment by benhuff** [comment]
> @benhuff do you mean to move all packages or just the noarch version? If the latter please check https://anaconda.org/conda-forge/h3-py/files and let me know if that is OK.

@ocefpaf thanks a lot! Only moving the noarch version to broken fixed the issue! 

I was just able to install it properly in a py38 conda environment. however, i am not sure why the tar.bz2 files that are uploaded to https://anaconda.org/conda-forge/h3-py/files are specifically for python 3.8. i used version pinning to restrict python in the host and run dependencies to ``python >2.7`` and rerendered with conda-smithy.

**Comment by ocefpaf** [comment]
That was build number 1, I fixed the build matrix in build number 2. The `>=` without the skip statement will use the latest python available and not a build matrix of the possible pythons.

**Comment by benhuff** [comment]
Thank you for the explanation. I will keep that in mind in the future 👍. I will close this issue now.
